Repository flant/addon-operator, pull requests merged in 2023-12, with the labels that each got.

#431 [Addon-operator ] Add debug routes
  pkg/addon-operator/bootstrap.go
  pkg/addon-operator/debug_server.go
Labels: dependencies

#433 Fix global values change
  pkg/module_manager/models/modules/values_storage.go
  pkg/module_manager/module_manager.go
  pkg/utils/values.go
  pkg/values/validation/schemas.go
Labels: bug, go

#439 Fix enabled modules
  pkg/module_manager/models/modules/global.go
  pkg/module_manager/module_manager.go
Labels: bug, go

#440 Fix modules events channel
  pkg/module_manager/module_manager.go
Labels: bug, go

#441 remove sort
  pkg/module_manager/models/modules/global.go
Labels: bug, go

#444 validate all enabled modules
  pkg/kube_config_manager/config/event.go
  pkg/kube_config_manager/kube_config_manager.go
  pkg/module_manager/models/modules/values_layered.go
  pkg/module_manager/models/modules/values_storage.go
  pkg/module_manager/module_manager.go
  pkg/utils/module_config.go
Labels: enhancement
