Repository flant/addon-operator, pull requests merged in 2023-11, with the labels that each got.

#421 Add strict check mode for MODULE_DIR/values.yaml files
  pkg/app/app.go
  pkg/module_manager/module_loader.go
Labels: enhancement

#427 Rollback changes to avoid races
  go.mod
  go.sum
  pkg/addon-operator/queue_test.go
  pkg/module_manager/module_manager.go
  pkg/utils/mergemap.go
Labels: bug, go

#429 fixed division by zero during module validation
  go.mod
  go.sum
Labels: dependencies
