Repository flant/addon-operator, pull requests merged in 2023-04, with the labels that each got.

#373 feat: Add stricter lint rules
  .golangci.yaml
  cmd/addon-operator/main.go
  pkg/addon-operator/bootstrap.go
  pkg/addon-operator/converge.go
  pkg/addon-operator/debug_server.go
  pkg/addon-operator/kube_client.go
  pkg/addon-operator/operator.go
  pkg/addon-operator/operator_test.go
  pkg/addon-operator/queue_test.go
  pkg/app/app.go
  pkg/app/debug-cmd.go
  pkg/helm/helm.go
  pkg/helm/helm3/helm3.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/helm/helm3lib/helm3lib_test.go
  pkg/helm/helm_test.go
  pkg/helm_resources_manager/helm_resources_manager.go
  pkg/helm_resources_manager/helm_resources_manager_test.go
  pkg/helm_resources_manager/resources_monitor.go
  pkg/helm_resources_manager/test/mock/mock.go
  pkg/kube_config_manager/access_config_map.go
  pkg/kube_config_manager/global_kube_config.go
  pkg/kube_config_manager/kube_config_manager.go
  pkg/kube_config_manager/kube_config_manager_test.go
  pkg/module_manager/global_hook.go
  pkg/module_manager/global_hook_config.go
  pkg/module_manager/global_hook_test.go
  pkg/module_manager/go_hook/go_hook.go
  pkg/module_manager/go_hook/metrics/collector.go
  pkg/module_manager/hook.go
  pkg/module_manager/hook_executor.go
  pkg/module_manager/hook_executor_test.go
  pkg/module_manager/module.go
  pkg/module_manager/module_hook.go
  pkg/module_manager/module_hook_config.go
  pkg/module_manager/module_loader.go
  pkg/module_manager/module_manager.go
  pkg/module_manager/module_manager_test.go
  pkg/task/hook_metadata.go
  pkg/task/test/task_metadata_test.go
  pkg/utils/module_config.go
  pkg/utils/module_config_test.go
  pkg/utils/module_list.go
  pkg/utils/values.go
  pkg/utils/values_patch.go
  pkg/utils/values_patch_test.go
  pkg/values/validation/defaulting.go
  pkg/values/validation/defaulting_test.go
  pkg/values/validation/validator.go
  sdk/registry_test.go
  sdk/sdk.go
  sdk/test/sdk_test.go
Labels: tests/run/all

#374 feat: Persist helm3lib Kubernetes clients
  pkg/helm/helm.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/helm/helm3lib/helm3lib_test.go
Labels: enhancement

#372 feat: Add debug flag for render command
  pkg/addon-operator/debug_server.go
  pkg/app/debug-cmd.go
  pkg/helm/client/client.go
  pkg/helm/helm3/helm3.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/helm/test/mock/mock.go
  pkg/module_manager/module.go
Labels: enhancement

#375 fix: Speedup ApplyIgnoreNonExistentPaths jsonpatch method
  .golangci.yaml
  go.mod
  pkg/utils/jsonpatch.go
  pkg/utils/values_patch.go
  pkg/utils/values_patch_test.go
Labels: tests/run/all

#381 Addon-operator method calls
  cmd/addon-operator/main.go
  pkg/addon-operator/bootstrap.go
  pkg/addon-operator/debug_server.go
  pkg/addon-operator/http_server.go
  pkg/addon-operator/operator.go
  pkg/addon-operator/operator_test.go
Labels: tests/run/all, release-note/enhancement
