Repository flant/addon-operator, pull requests merged in 2023-09, with the labels that each got.

#404 Fix panic on defaulting an array without items schema
  pkg/module_manager/module_manager_test.go
  pkg/utils/values_patch_test.go
  pkg/values/validation/defaulting.go
  pkg/values/validation/defaulting_test.go
  pkg/values/validation/validator_test.go
Labels: release-note/bug

#405 Clean up tiller mentions from docs
  README.md
  docs/src/README.md
Labels: bug

#412 Disable purging unknown helm releases
  pkg/addon-operator/operator.go
  pkg/addon-operator/operator_test.go
Labels: enhancement

#413 [fix] Modules purge
  pkg/addon-operator/operator.go
  pkg/module_manager/module_manager.go
  pkg/module_manager/module_manager_test.go
Labels: go, release-note/enhancement
