Repository flant/addon-operator, pull requests merged in 2023-10, with the labels that each got.

#414 add update status
  go.mod
  go.sum
  pkg/module_manager/hook_executor.go
  pkg/module_manager/module_hook.go
Labels: release-note/new-feature

#418 Update mergemap to reduce memory allocations
  go.mod
  go.sum
  pkg/utils/mergemap.go
  pkg/utils/mergemap_test.go
  pkg/utils/values.go
Labels: enhancement

#419 Dynamic values patch improvements
  pkg/module_manager/go_hook/patchable_values.go
  pkg/module_manager/module_manager.go
  pkg/utils/module_config.go
  pkg/utils/values_patch.go
  pkg/utils/values_patch_test.go
Labels: enhancement

#422 Fix ApplyPatch function
  pkg/utils/values_patch.go
Labels: bug, go

#425 Separate metric storages
  go.mod
  go.sum
  pkg/addon-operator/bootstrap.go
  pkg/addon-operator/http_server.go
  pkg/addon-operator/metrics.go
  pkg/addon-operator/operator.go
Labels: enhancement, go
