Repository flant/addon-operator, pull requests merged in 2024-04, with the labels that each got.

#468 Cli command to show requirements
  pkg/addon-operator/bootstrap.go
  pkg/addon-operator/operator.go
Labels: dependencies

#472 Refactor list logic for helm3 and helm3lib
  pkg/addon-operator/operator.go
  pkg/helm/client/client.go
  pkg/helm/helm.go
  pkg/helm/helm3/helm3.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/helm/helm3lib/helm3lib_test.go
  pkg/helm/helm_test.go
  pkg/helm/test/mock/mock.go
  pkg/module_manager/module_manager.go
Labels: enhancement, go

#469 Provide a way of updating a module's static values
  pkg/module_manager/loader/fs/fs.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/values_storage.go
  pkg/module_manager/module_manager.go
Labels: enhancement
