Repository flant/addon-operator, pull requests merged in 2024-03, with the labels that each got.

#455 make sure all hooks have a hook controller set
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/hook_storage.go
  pkg/module_manager/module_manager.go
  pkg/module_manager/module_manager_hooks.go
Labels: enhancement

#452 Exported MetricStorage from shell operator
  pkg/addon-operator/operator.go
Labels: release-note/ignore

#464 fix camelCase to kebab-case conversion
  go.mod
  go.sum
  pkg/addon-operator/operator.go
  pkg/kube_config_manager/kube_config_manager_test.go
  pkg/utils/values.go
  pkg/utils/values_test.go
Labels: bug

#462 Send events at module state change
  pkg/addon-operator/operator.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/events/events.go
  pkg/module_manager/module_manager.go
Labels: release-note/new-feature
