Repository flant/addon-operator, pull requests merged in 2024-05, with the labels that each got.

#470 [addon-operator] Get rid of ValuesValidator structure
  .gitignore
  pkg/module_manager/loader/fs/fs.go
  pkg/module_manager/loader/fs/fs_test.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/basic_test.go
  pkg/module_manager/models/modules/global.go
  pkg/module_manager/models/modules/values_defaulting_transformers.go
  pkg/module_manager/models/modules/values_storage.go
  pkg/module_manager/models/modules/values_storage_test.go
  pkg/module_manager/module_manager.go
  pkg/module_manager/module_manager_hooks.go
  pkg/module_manager/module_manager_test.go
  pkg/module_manager/utils.go
  pkg/values/validation/defaulting_test.go
  pkg/values/validation/extend_test.go
  pkg/values/validation/required_test.go
  pkg/values/validation/schemas.go
  pkg/values/validation/schemas_test.go
  pkg/values/validation/validator.go
  pkg/values/validation/validator_test.go
Labels: enhancement

#476 fix error message
  pkg/values/validation/schemas.go
Labels: release-note/ignore

#478 [addon-operator] add missing context to operator
  cmd/addon-operator/main.go
  pkg/addon-operator/operator.go
Labels: enhancement

#477 fix panic if hookcontrollers aren't set when disabling the module's hooks
  pkg/module_manager/module_manager.go
Labels: bug
