Repository flant/addon-operator, pull requests merged in 2024-12, with the labels that each got.

#533 change batch hook name
  pkg/module_manager/models/modules/basic.go
Labels: bug

#534 rollback to global values in constructors
  pkg/module_manager/loader/fs/fs.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/basic_test.go
Labels: bug

#538 replace patchvalues with interface
  pkg/module_manager/go_hook/go_hook.go
Labels: enhancement

#539 add options to modules
  pkg/addon-operator/debug_server.go
  pkg/module_manager/loader/fs/fs.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/basic_test.go
  pkg/module_manager/models/modules/global.go
  pkg/module_manager/models/modules/helm.go
  pkg/module_manager/models/modules/module_options.go
  pkg/module_manager/module_manager.go
  pkg/module_manager/module_manager_hooks.go
Labels: enhancement

#542 bump logger and shell operator
  cmd/addon-operator/main.go
  go.mod
  go.sum
  pkg/addon-operator/admission_http_server.go
  pkg/module_manager/models/modules/basic.go
Labels: dependencies

#543 Fix/return global value to proxy json hook
  pkg/module_manager/models/hooks/kind/batch_hook.go
  pkg/module_manager/models/hooks/kind/shellhook.go
Labels: bug

#544 Feat/load config interface
  Makefile
  pkg/module_manager/go_hook/go_hook.go
  pkg/module_manager/models/hooks/dependency.go
  pkg/module_manager/models/hooks/global_hook.go
  pkg/module_manager/models/hooks/global_hook_config.go
  pkg/module_manager/models/hooks/global_hook_config_test.go
  pkg/module_manager/models/hooks/kind/batch_hook.go
  pkg/module_manager/models/hooks/kind/batch_hook_test.go
  pkg/module_manager/models/hooks/kind/gohook.go
  pkg/module_manager/models/hooks/kind/shellhook.go
  pkg/module_manager/models/hooks/kind/shellhook_test.go
  pkg/module_manager/models/hooks/module_hook.go
  pkg/module_manager/models/hooks/module_hook_config.go
  pkg/module_manager/models/hooks/module_hook_config_test.go
Labels: enhancement

#537 [scheduler] add topological extender type
  pkg/addon-operator/operator.go
  pkg/module_manager/module_manager.go
  pkg/module_manager/scheduler/extenders/extenders.go
  pkg/module_manager/scheduler/extenders/mock/extenders_mock.go
  pkg/module_manager/scheduler/extenders/script_enabled/script.go
  pkg/module_manager/scheduler/extenders/script_enabled/script_test.go
  pkg/module_manager/scheduler/node/node.go
  pkg/module_manager/scheduler/scheduler.go
  pkg/module_manager/scheduler/scheduler_test.go
  pkg/task/hook_metadata.go
Labels: enhancement

#548 consider ModuleEnsureCRDs tasks as converge tasks
  pkg/addon-operator/converge/converge.go
Labels: bug

#546 feat: replace deprecated logger methods
  .golangci.yaml
  cmd/addon-operator/main.go
  examples/700-go-hook/global-hooks/global-go-hook.go
  examples/700-go-hook/modules/001-module-go-hooks/hooks/go_hooks.go
  pkg/addon-operator/admission_http_server.go
  pkg/addon-operator/bootstrap.go
  pkg/addon-operator/operator.go
  pkg/addon-operator/operator_test.go
  pkg/addon-operator/queue.go
  pkg/helm/helm.go
  pkg/helm/helm3/helm3.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/helm_resources_manager/helm_resources_manager.go
  pkg/helm_resources_manager/resources_monitor.go
  pkg/kube_config_manager/backend/configmap/configmap.go
  pkg/kube_config_manager/kube_config_manager.go
  pkg/module_manager/go_hook/patchable_values.go
  pkg/module_manager/loader/fs/fs.go
  pkg/module_manager/models/hooks/kind/batch_hook.go
  pkg/module_manager/models/hooks/kind/shellhook.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/global.go
  pkg/module_manager/models/modules/helm.go
  pkg/module_manager/models/modules/synchronization_state.go
  pkg/module_manager/module_manager.go
  pkg/module_manager/scheduler/extenders/dynamically_enabled/dynamic.go
  pkg/module_manager/scheduler/extenders/script_enabled/script.go
  pkg/module_manager/scheduler/extenders/static/static.go
  pkg/module_manager/scheduler/scheduler.go
  pkg/task/hook_metadata.go
  pkg/utils/loader.go
  pkg/utils/values.go
  pkg/values/validation/schemas.go
Labels: enhancement, go
