Repository flant/addon-operator, pull requests merged in 2024-11, with the labels that each got.

#517 [module manager] add module info metrics
  Dockerfile
  go.mod
  go.sum
  pkg/addon-operator/operator_test.go
  pkg/module_manager/module_manager.go
Labels: enhancement

#516 [addon-operator] Replace Logrus with slog
  .golangci.yaml
  cmd/addon-operator/main.go
  examples/700-go-hook/global-hooks/global-go-hook.go
  examples/700-go-hook/modules/001-module-go-hooks/hooks/go_hooks.go
  go.mod
  go.sum
  pkg/addon-operator/admission_http_server.go
  pkg/addon-operator/bootstrap.go
  pkg/addon-operator/debug_server.go
  pkg/addon-operator/kube_client.go
  pkg/addon-operator/operator.go
  pkg/addon-operator/operator_test.go
  pkg/addon-operator/queue.go
  pkg/addon-operator/queue_test.go
  pkg/helm/helm.go
  pkg/helm/helm3/helm3.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/helm/helm3lib/helm3lib_test.go
  pkg/helm/helm_test.go
  pkg/helm/test/mock/mock.go
  pkg/helm_resources_manager/helm_resources_manager.go
  pkg/helm_resources_manager/resources_monitor.go
  pkg/kube_config_manager/backend/configmap/configmap.go
  pkg/kube_config_manager/kube_config_manager.go
  pkg/kube_config_manager/kube_config_manager_test.go
  pkg/module_manager/go_hook/go_hook.go
  pkg/module_manager/go_hook/patchable_values.go
  pkg/module_manager/loader/fs/fs.go
  pkg/module_manager/loader/fs/fs_test.go
  pkg/module_manager/models/hooks/kind/gohook.go
  pkg/module_manager/models/hooks/kind/shellhook.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/basic_test.go
  pkg/module_manager/models/modules/global.go
  pkg/module_manager/models/modules/helm.go
  pkg/module_manager/models/modules/synchronization_state.go
  pkg/module_manager/module_manager.go
  pkg/module_manager/module_manager_hooks.go
  pkg/module_manager/module_manager_test.go
  pkg/module_manager/scheduler/extenders/dynamically_enabled/dynamic.go
  pkg/module_manager/scheduler/extenders/script_enabled/script.go
  pkg/module_manager/scheduler/extenders/static/static.go
  pkg/module_manager/scheduler/scheduler.go
  pkg/module_manager/scheduler/scheduler_test.go
  pkg/task/hook_metadata.go
  pkg/utils/loader.go
  pkg/utils/merge_labels.go
  pkg/utils/stdliblogtolog/adapter.go
  pkg/utils/stdliblogtolog/adapter_test.go
  pkg/utils/stdliblogtologrus/adapter.go
  pkg/utils/values.go
  pkg/values/validation/schemas.go
  sdk/test/simple_operator/global-hooks/go-hook.go
  sdk/test/simple_operator/modules/001-module-one/hooks/module-one-hook.go
  sdk/test/simple_operator/modules/002-module-two/hooks/level1/sublevel/sub-sub-hook.go
Labels: dependencies

#519 [addon-operator] Fix/module name
  pkg/helm_resources_manager/helm_resources_manager.go
  pkg/helm_resources_manager/resources_monitor.go
Labels: bug

#520 [addon-operator] Fix/purge nil
  pkg/module_manager/module_manager.go
Labels: enhancement, go

#522 Increased CRDs Installer buffer size
  pkg/addon-operator/ensure_crds.go
Labels: release-note/ignore

#521 [addon-operator] fix/rename source field
  .golangci.yaml
  go.mod
  go.sum
  pkg/addon-operator/kube_client.go
  pkg/addon-operator/operator.go
  pkg/kube_config_manager/backend/configmap/configmap.go
  pkg/kube_config_manager/config/config.go
  pkg/kube_config_manager/kube_config_manager_test.go
Labels: enhancement

#526 Improved CRDs Installer
  pkg/addon-operator/ensure_crds.go
Labels: release-note/ignore

#527 fix: compare crd spec, labels and annotations before update
  .golangci.yaml
  go.mod
  pkg/addon-operator/ensure_crds.go
  pkg/utils/values_test.go
Labels: release-note/enhancement

#528 Improved CRDs Installer
  pkg/addon-operator/ensure_crds.go
Labels: release-note/ignore

#530 Update dependabot.yaml
  .github/dependabot.yaml
Labels: dependencies
