Repository flant/addon-operator, pull requests merged in 2024-10, with the labels that each got.

#506 Add fake CRD modules to the enabledModules list and fix merge values procedure
  .github/workflows/build.yaml
  .github/workflows/lint.yaml
  .github/workflows/tests.yaml
  Dockerfile
  go.mod
  go.sum
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/values_defaulting_transformers.go
  pkg/module_manager/models/modules/values_layered_test.go
  pkg/module_manager/models/modules/values_storage.go
  pkg/module_manager/module_manager.go
  pkg/utils/mergemap.go
  pkg/utils/values.go
Labels: bug, enhancement

#508 Upgrade kube-client and helm
  .github/workflows/lint.yaml
  go.mod
  go.sum
  pkg/kube_config_manager/backend/configmap/configmap.go
  pkg/module_manager/go_hook/metrics/collector.go
  pkg/module_manager/scheduler/extenders/script_enabled/script.go
  pkg/utils/module_config_test.go
Labels: dependencies

#513 [module-manager] Disable modules hooks correctly
  go.mod
  go.sum
  pkg/module_manager/models/modules/hook_storage.go
  pkg/module_manager/scheduler/scheduler.go
Labels: bug

#515 [chore] bump shell operator
  go.mod
  go.sum
Labels: bug

#514 [helm_resources_manager] use cache instead of a plain client
  Dockerfile
  cmd/addon-operator/main.go
  cmd/post-renderer/main.go
  docs/src/RUNNING.md
  go.mod
  go.sum
  pkg/addon-operator/kube_client.go
  pkg/addon-operator/operator.go
  pkg/helm/helm.go
  pkg/helm/helm3/helm3.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/helm/helm3lib/helm3lib_test.go
  pkg/helm/helm_test.go
  pkg/helm/post_renderer/post_renderer.go
  pkg/helm/post_renderer/post_renderer_test.go
  pkg/helm/version_detect.go
  pkg/helm/version_detect_test.go
  pkg/helm_resources_manager/helm_resources_manager.go
  pkg/helm_resources_manager/helm_resources_manager_test.go
  pkg/helm_resources_manager/resources_monitor.go
Labels: enhancement
