Repository flant/addon-operator, pull requests merged in 2025-04, with the labels that each got.

#579 Add module Unmanaged mode
  cmd/post-renderer/main.go
  go.mod
  go.sum
  pkg/addon-operator/debug_server.go
  pkg/addon-operator/kube_client.go
  pkg/addon-operator/operator.go
  pkg/app/debug-cmd.go
  pkg/helm/client/client.go
  pkg/helm/helm.go
  pkg/helm/helm3/helm3.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/helm/helm3lib/helm3lib_test.go
  pkg/helm/post_renderer/post_renderer.go
  pkg/helm/post_renderer/post_renderer_test.go
  pkg/helm/test/mock/mock.go
  pkg/helm_resources_manager/helm_resources_manager.go
  pkg/helm_resources_manager/test/mock/mock.go
  pkg/kube_config_manager/backend/configmap/configmap.go
  pkg/kube_config_manager/config/config.go
  pkg/kube_config_manager/kube_config_manager.go
  pkg/kube_config_manager/kube_config_manager_test.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/helm.go
  pkg/module_manager/module_manager.go
  pkg/module_manager/module_manager_hooks.go
  pkg/module_manager/scheduler/extenders/static/static.go
  pkg/utils/module_config.go
  pkg/utils/values_patch.go
Labels: enhancement

#588 refactor: rename ManagementState to MaintenanceState across the module
  pkg/addon-operator/operator.go
  pkg/kube_config_manager/backend/configmap/configmap.go
  pkg/kube_config_manager/config/config.go
  pkg/kube_config_manager/kube_config_manager.go
  pkg/kube_config_manager/kube_config_manager_test.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/helm.go
  pkg/module_manager/module_manager.go
  pkg/utils/module_config.go
Labels: enhancement, go

#583 feat: add GetReleaseChecksum method and update UpgradeRelease signature
  pkg/helm/client/client.go
  pkg/helm/helm3/helm3.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/helm/helm3lib/helm3lib_test.go
  pkg/helm/helm_test.go
  pkg/helm/test/mock/mock.go
  pkg/module_manager/models/modules/helm.go
Labels: enhancement

#584 feat: improve error message for invalid module hook configuration
  pkg/module_manager/models/modules/basic.go
Labels: enhancement

#589 feat: update shell-operator and some dependencies
  .github/workflows/build.yaml
  .github/workflows/tests.yaml
  Dockerfile
  go.mod
  go.sum
  pkg/addon-operator/converge/converge.go
  pkg/addon-operator/http_server.go
  pkg/addon-operator/operator.go
  pkg/addon-operator/operator_test.go
  pkg/app/app.go
Labels: dependencies

#574 [addon-operator] refactoring
  cmd/addon-operator/main.go
  go.mod
  go.sum
  pkg/addon-operator/bootstrap.go
  pkg/addon-operator/debug_server.go
  pkg/addon-operator/handler_manager_events.go
  pkg/addon-operator/handler_module_manager.go
  pkg/addon-operator/http_server.go
  pkg/addon-operator/metrics.go
  pkg/addon-operator/operator.go
  pkg/addon-operator/operator_test.go
  pkg/module_manager/models/modules/global.go
  pkg/module_manager/module_manager.go
  pkg/module_manager/scheduler/scheduler.go
Labels: enhancement

#578 [addon-operator] feat/minor improvements two
  go.mod
  go.sum
  pkg/addon-operator/bootstrap.go
  pkg/addon-operator/converge/converge.go
  pkg/addon-operator/debug_server.go
  pkg/addon-operator/handler_manager_events.go
  pkg/addon-operator/metrics.go
  pkg/addon-operator/operator.go
  pkg/addon-operator/operator_test.go
  pkg/labels.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/global.go
  pkg/module_manager/models/modules/helm.go
  pkg/module_manager/models/modules/synchronization_state.go
  pkg/task/apply-kube-config-values/task.go
  pkg/task/converge-modules/task.go
  pkg/task/discover-helm-release/task.go
  pkg/task/global-hook-enable-kubernetes-bindings/task.go
  pkg/task/global-hook-enable-schedule-bindings/task.go
  pkg/task/global-hook-run/task.go
  pkg/task/global-hook-wait-kubernetes-synchronization/task.go
  pkg/task/helpers/helpers.go
  pkg/task/module-delete/task.go
  pkg/task/module-ensure-crds/task.go
  pkg/task/module-hook-run/task.go
  pkg/task/module-purge/task.go
  pkg/task/module-run/task.go
  pkg/task/parallel-module-run/task.go
  pkg/task/parallel/parallel.go
  pkg/task/queue/queue.go
  pkg/task/service/converge.go
  pkg/task/service/logs.go
  pkg/task/service/metric.go
  pkg/task/service/service.go
  pkg/task/task.go
Labels: enhancement

#592 [feature] add cel validation for module values
  go.mod
  go.sum
  pkg/values/validation/cel/cel.go
  pkg/values/validation/schemas.go
  pkg/values/validation/validator_test.go
Labels: enhancement

#598 [addon-operator] 1.6 maintenance mode restart fix
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/helm.go
  pkg/module_manager/module_manager.go
Labels: bug

#596 [addon-operator] fix/maintenance mode restart fix
  .github/workflows/build.yaml
  .github/workflows/tests.yaml
  Dockerfile
  go.mod
  go.sum
  pkg/helm/client/client.go
  pkg/helm/helm3/helm3.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/helm.go
  pkg/module_manager/module_manager.go
Labels: bug

#597 [addon-operator] Remove helm binary using
  docs/src/RUNNING.md
  pkg/helm/helm.go
  pkg/helm/helm3/helm3.go
  pkg/helm/helm_test.go
  pkg/helm/testdata/helm-fake/faulty/helm
  pkg/helm/testdata/helm-fake/helm2/helm
  pkg/helm/testdata/helm-fake/helm3/helm
  pkg/helm/version_detect.go
  pkg/helm/version_detect_test.go
  pkg/task/global-hook-run/task.go
Labels: enhancement

#599 module run response fail fix
  pkg/task/module-run/task.go
Labels: bug
