Repository flant/addon-operator, pull requests merged in 2025-03, with the labels that each got.

#567 Add graph text description handler
  pkg/addon-operator/debug_server.go
  pkg/module_manager/module_manager.go
  pkg/module_manager/scheduler/scheduler.go
Labels: enhancement, go

#566 [addon-operator] fix nil, add error handling, fix logger
  pkg/addon-operator/debug_server.go
  pkg/module_manager/models/modules/helm.go
  pkg/module_manager/module_manager.go
Labels: enhancement

#568 [scheduler] fix out of order vertices traversing
  pkg/module_manager/scheduler/extenders/mock/extenders_mock.go
  pkg/module_manager/scheduler/node/mock/node_mock.go
  pkg/module_manager/scheduler/node/node.go
  pkg/module_manager/scheduler/scheduler.go
  pkg/module_manager/scheduler/scheduler_test.go
  pkg/module_manager/scheduler/testdata/20-cert-manager/enabled
  pkg/module_manager/scheduler/testdata/30-openstack-cloud-provider/enabled
  pkg/module_manager/scheduler/testdata/909-test-echo/enabled
Labels: bug

#560 chrooted bash executor
  go.mod
  go.sum
  pkg/addon-operator/admission_http_server.go
  pkg/addon-operator/bootstrap.go
  pkg/addon-operator/operator.go
  pkg/app/app.go
  pkg/helm_resources_manager/helm_resources_manager.go
  pkg/module_manager/environment_manager/evironment_manager.go
  pkg/module_manager/environment_manager/evironment_manager_test.go
  pkg/module_manager/models/hooks/dependency.go
  pkg/module_manager/models/hooks/kind/batch_hook.go
  pkg/module_manager/models/hooks/kind/batch_hook_test.go
  pkg/module_manager/models/hooks/kind/shellhook.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/basic_test.go
  pkg/module_manager/models/modules/global.go
  pkg/module_manager/module_manager.go
  pkg/module_manager/scheduler/extenders/script_enabled/script.go
  pkg/module_manager/scheduler/extenders/static/static.go
  pkg/utils/chroot.go
Labels: enhancement

#569 [addon-operator] feat/new-patch-collector-interface
  .github/workflows/build.yaml
  .github/workflows/lint.yaml
  .github/workflows/tests.yaml
  go.mod
  go.sum
  pkg/addon-operator/kube_client.go
  pkg/addon-operator/metrics.go
  pkg/addon-operator/operator.go
  pkg/addon-operator/operator_test.go
  pkg/addon-operator/queue_test.go
  pkg/module_manager/environment_manager/evironment_manager.go
  pkg/module_manager/environment_manager/mount.go
  pkg/module_manager/environment_manager/mount_linux.go
  pkg/module_manager/go_hook/go_hook.go
  pkg/module_manager/models/hooks/dependency.go
  pkg/module_manager/models/hooks/kind/kind.go
  pkg/module_manager/models/hooks/module_hook_config.go
  pkg/module_manager/module_manager.go
Labels: enhancement

#575 [addon-operator] bump shell operator
  go.mod
  go.sum
Labels: enhancement

#571 [shell-hooks] consider python vevn when running python scripts
  pkg/module_manager/models/hooks/kind/shellhook.go
  pkg/module_manager/models/modules/basic.go
Labels: enhancement

#580 Use force while upgrade templates
  pkg/helm/helm3/helm3.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/module_manager/environment_manager/mount.go
  pkg/module_manager/models/modules/global.go
  pkg/module_manager/models/modules/helm.go
Labels: enhancement, go

#581 Make helm3lib by default
  pkg/helm/helm_test.go
  pkg/helm/version_detect.go
  pkg/helm/version_detect_test.go
Labels: enhancement

#582 Rollback force flag
  pkg/helm/helm3/helm3.go
  pkg/helm/helm3lib/helm3lib.go
Labels: bug, go
