Repository flant/addon-operator, pull requests merged in 2025-09, with the labels that each got.

#667 [fix] inject module registry to values
  pkg/module_manager/models/modules/values_storage.go
  pkg/values/validation/schemas.go
Labels: go, release-note/enhancement

#666 [addon-operator] Switch to nelm
  go.mod
  go.sum
  pkg/addon-operator/debug_server.go
  pkg/helm/client/client.go
  pkg/helm/helm.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/helm/helm_test.go
  pkg/helm/nelm/logger.go
  pkg/helm/nelm/nelm.go
  pkg/helm/test/mock/mock.go
  pkg/helm/version_detect.go
  pkg/helm/version_detect_test.go
  pkg/module_manager/models/modules/helm.go
Labels: enhancement

#675 Don't disable monitors before after delete hook run
  pkg/module_manager/module_manager.go
  pkg/task/tasks/converge-modules/task.go
Labels: enhancement

#676 [addon-operator] remove search hooks log duplicates
  pkg/module_manager/models/modules/global.go
Labels: bug
