Repository flant/addon-operator, pull requests merged in 2025-01, with the labels that each got.

#545 [ci] add nonamedreturns linter
  .golangci.yaml
  pkg/addon-operator/bootstrap.go
  pkg/addon-operator/operator.go
  pkg/helm/helm3/helm3.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/helm/post_renderer/post_renderer.go
  pkg/kube_config_manager/backend/configmap/configmap.go
  pkg/module_manager/loader/fs/fs.go
  pkg/module_manager/models/hooks/kind/batch_hook.go
  pkg/module_manager/models/hooks/kind/gohook.go
  pkg/module_manager/models/hooks/kind/shellhook.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/global.go
  pkg/module_manager/module_manager.go
  pkg/task/hook_metadata.go
  pkg/utils/fswalk.go
  pkg/utils/loader.go
  pkg/utils/module_list.go
  pkg/utils/stdliblogtolog/adapter.go
  pkg/values/validation/schemas.go
Labels: enhancement, go

#549 refresh states of disabled modules on first converge
  pkg/addon-operator/operator.go
Labels: enhancement

#551 [helm] add SkipCRDs helm flag
  pkg/helm/helm3/helm3.go
  pkg/helm/helm3lib/helm3lib.go
Labels: enhancement

#550 move crd installer to module sdk
  go.mod
  go.sum
  pkg/addon-operator/ensure_crds.go
  pkg/module_manager/models/hooks/kind/shellhook.go
  pkg/module_manager/models/hooks/kind/shellhook_test.go
Labels: enhancement, dependencies

#555 fix nil
  pkg/module_manager/models/hooks/kind/batch_hook.go
  pkg/module_manager/models/hooks/kind/gohook.go
Labels: bug, go

#556 fix nil
  pkg/module_manager/models/hooks/kind/gohook.go
Labels: bug

#559 [batch-hook] fix version bug
  pkg/module_manager/models/hooks/kind/batch_hook.go
Labels: bug
