Repository flant/addon-operator, pull requests merged in 2025-06, with the labels that each got.

#608 feat: remove generation from diff output
  pkg/addon-operator/debug_server.go
  pkg/addon-operator/diff/diff.go
Labels: enhancement, go

#617 [fix] fix maintenance default value
  pkg/utils/module_config.go
Labels: bug, go

#621 [fix] 1.7 maintaince state
  pkg/utils/module_config.go
Labels: bug

#613 [addon-operator] Add readiness probe to batch hook
  go.mod
  go.sum
  pkg/addon-operator/metrics.go
  pkg/addon-operator/operator.go
  pkg/addon-operator/operator_test.go
  pkg/labels.go
  pkg/module_manager/models/hooks/kind/batch_hook.go
  pkg/module_manager/models/hooks/kind/batch_hook_test.go
  pkg/module_manager/models/hooks/kind/config.go
  pkg/module_manager/models/hooks/kind/shellhook.go
  pkg/module_manager/models/modules/basic.go
  pkg/module_manager/models/modules/global.go
  pkg/module_manager/models/modules/synchronization_state.go
  pkg/module_manager/module_manager_hooks.go
  pkg/task/service/metric.go
  pkg/task/service/service.go
  pkg/task/tasks/apply-kube-config-values/task.go
  pkg/task/tasks/converge-modules/task.go
  pkg/task/tasks/discover-helm-release/task.go
  pkg/task/tasks/global-hook-enable-kubernetes-bindings/task.go
  pkg/task/tasks/global-hook-enable-schedule-bindings/task.go
  pkg/task/tasks/global-hook-run/task.go
  pkg/task/tasks/global-hook-wait-kubernetes-synchronization/task.go
  pkg/task/tasks/module-delete/task.go
  pkg/task/tasks/module-ensure-crds/task.go
  pkg/task/tasks/module-hook-run/task.go
  pkg/task/tasks/module-purge/task.go
  pkg/task/tasks/module-run/task.go
  pkg/task/tasks/parallel-module-run/task.go
Labels: enhancement
