Repository flant/addon-operator, pull requests merged in 2025-05, with the labels that each got.

#601 Feat/add output option to status converge
  pkg/addon-operator/http_server.go
Labels: enhancement

#602 [addon-operator] tests: added ListReleases to LibClient for testing
  .github/workflows/lint.yaml
  .golangci.yaml
  pkg/addon-operator/debug_server.go
  pkg/addon-operator/handler_module_manager.go
  pkg/addon-operator/http_server.go
  pkg/addon-operator/queue_test.go
  pkg/helm/helm3lib/helm3lib.go
  pkg/helm/helm3lib/helm3lib_test.go
  pkg/module_manager/models/modules/basic.go
Labels: go, release-note/ignore

#607 [addon-operator] bump shell-operator
  go.mod
  go.sum
Labels: dependencies

#570 [addon operator] feat/replace hook input interfaces
  examples/700-go-hook/modules/001-module-go-hooks/hooks/go_hooks.go
  pkg/addon-operator/bootstrap.go
  pkg/module_manager/go_hook/filter_result.go
  pkg/module_manager/go_hook/filter_result_test.go
  pkg/module_manager/go_hook/go_hook.go
  pkg/module_manager/go_hook/logger.go
  pkg/module_manager/go_hook/metrics/collector.go
  pkg/module_manager/go_hook/patchable_values.go
  pkg/module_manager/models/hooks/kind/gohook.go
  pkg/module_manager/models/modules/basic_test.go
  pkg/module_manager/models/modules/global.go
  pkg/module_manager/models/modules/values_storage_test.go
  pkg/utils/jsonpatch.go
  pkg/utils/values_patch.go
  pkg/utils/values_patch_test.go
Labels: enhancement

#612 [addon-operator] fix crd discoverer
  pkg/task/discover-crds/service.go
  pkg/task/module-ensure-crds/task.go
  pkg/task/service/service.go
Labels: enhancement
